train:
  num_epochs: 100
  lr: 3e-4
  batch_size: 64

model:
  in_dim: 3
  embed_dim: 96
  patch_size: 2
  num_patches: 256
  num_layers: 6
  num_classes: 10
  num_heads: 8

data_dir: ${hydra:runtime.cwd}/data
